site_name: DataLink
site_description: Linked Data Visualization and Management
site_url: https://yourdomain.com/
use_directory_urls: false

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    - navigation.footer
    - header.autohide
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - tags
  - gen-files:
      scripts:
        - generate_pages.py
  - macros:
      module_name: main

nav:
  - Home: index.md
  - Entities: entities/
  - About: about.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/page.css
  - stylesheets/network.css
  - stylesheets/entities/index.css
  - stylesheets/entities/detail.css
  - stylesheets/entities/gallery.css

# extra_javascript:
#   - javascripts/gallery.js

extra:
  generator: false

copyright: Copyright &copy; 2025 - Now Junho